P5AP-81
makeitMVPadmin/LAP5_Accountabuddy pull request #14
Opened 2024-10-18 16:30 UTC by truittjanney

For this issue, I wrote the API routes for the backend using Firebase. This is done so it can be integrated for the front end.

Jagadeep has looked over and reviewed the code as well.

Let us know your thoughts!

2024-10-19 00:21 UTC, mohanhastidev requested changes
Fix the app.js

2024-10-19 00:21 UTC, mohanhastidev commented on src/App.js
> +        <Route path="/Testa" element={<LoadingPage />} />
This line already exists on line 21. Remove this

2024-10-19 00:21 UTC, mohanhastidev commented on src/utils/Functions/functions.js
> +
remove the commented code if not needed

2024-10-19 00:21 UTC, mohanhastidev commented on src/utils/Functions/functions.js
> +// !!!!! Old Code !!!!!
you might need this to fetch all the challenges data from firebase

2024-10-22 16:46 UTC, robester0403 reviewed
just some quick notes

2024-10-22 16:46 UTC, robester0403 commented on src/pages/TestPage/TestPage.jsx
> +<<<<<<< HEAD
remove this

2024-10-22 16:46 UTC, robester0403 commented on src/pages/TestPage/TestPage.jsx
> +=======
Remove this

2024-10-22 16:46 UTC, robester0403 commented on src/pages/TestPage/TestPage.jsx
> +>>>>>>> 3c2c5829efbb1817eefd755f8a15c335bce18236
remove this

2024-10-22 16:46 UTC, robester0403 commented on src/routes/routes.py
> +# from flask import Blueprint, request, jsonify
Delete this page

2024-10-22 16:46 UTC, robester0403 commented on src/utils/Functions/functions.js
> +// const bcrypt = require('bcrypt'); // For hashing passwords
Remove this

2024-10-22 16:46 UTC, robester0403 commented on src/utils/Functions/functions.js
> +    // Step 2: Get the user document from Firestore
You don't need comments for this code

2024-10-22 16:46 UTC, robester0403 commented on src/utils/Functions/functions.js
> +    } = userData; // Extract specific fields
Remove all comments.

Also you don't need the Steps #. I'd argue you don't even need the names for any of these functions

2024-10-22 16:46 UTC, robester0403 commented on src/utils/Functions/functions.js
> +// UPDATE USER DETAILS
You would not need this comment as the function is called updateUserDetails. Delete all names similar to this.

2024-10-22 16:46 UTC, robester0403 commented on src/pages/TestPage/TestPage.jsx
> +    const fetchData = async () => {
If you are defining the function, you might as well move it out of the useEffect and place it to the top or the bottom of the file. Or just not define it at all

2024-10-22 16:46 UTC, robester0403 commented on src/pages/TestPage/TestPage.jsx
> +      console.log(result[0]);
Remove console log

2024-10-22 16:46 UTC, robester0403 commented on src/pages/TestPage/TestPage.jsx
> +    fetchData();
Case in point you define it just to call it here. Why don't you just put the logic into the use effect without defining it as a function

2025-09-08 21:39 UTC, closed without merging